version: "3.7"

services:

  db-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: reborn
      MYSQL_USER: reborn
      MYSQL_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Seoul"
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
  test-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/reborn
      SPRING_DATASOURCE_USERNAME: reborn
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      TZ: "Asia/Seoul"

    ports:
      - 8080:8080
    depends_on:
      - db-mysql
      - db-redis
    networks:
      - springboot-mysql-net
  db-redis:
    container_name: redis
    image: redis

    ports:
      - 6379:6379
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge
